# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20abd486f233407315cc780abd7db9c5c4b524876fe4d4d29b3e39b4771f153d232276628eccb10c5e745b5efaecc6ca7f3e14dfee73918024721134e5c40827

test:
  secret_key_base: a8873ac2b356cf9a0807f846d8b427c5f024a5dd38ff419b89c94f4c5313fc80d99d997d2a792d57c3ded112030ccc85c775a615af226384a88fc0ce49485b2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
